name = "EquivariantOperators"
uuid = "e0aa4542-b1ed-4e6a-a09e-9c4627a9da65"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "0.1.3"

"deps"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
# Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
Plots="91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
StaticArrays="90137ffa-7385-5640-81b9-e52037218182"

"compat"
julia = "1.7, 5"        # "3.0.0, âˆž), no upper bound (bad)
# DSP = "0.7.5"
# Flux = "0.13.1,5"
# Functors = "0.2.8,5"
# UnPack = "1.0.2,5" # Zygote = "0.6.40"
# Plots="1.0,5"
# ImageFiltering="0.7.1,5"
# StaticArrays="1,5"
